branch-defaults:
  master:
    environment: Cloudtype-env
environment-defaults:
  Cloudtype-env:
    branch: master
    repository: origin
global:
  application_name: cloudtype
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:us-west-2::platform/Node.js running on
    64bit Amazon Linux/4.13.1
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
